<div>
    <h2>Math operations in python</h2>
</div>

<div>
    <h1>An Introduction to Python</h1>
</div>

<p>
    Python has several built-in data structures:
    <ul>
        <li><strong>Integers</strong>: Whole numbers (e.g., 1, 20, 100)</li>
        <li><strong>Floats</strong>: Decimal numbers (e.g., 1.5, 3.09)</li>
        <li><strong>Strings</strong>: Text data (e.g., "Hello, World!")</li>
        <li><strong>Lists</strong>: Ordered collections of values (e.g., ["Tehran", "Shiraz", "Yazd"])</li>
        <li><strong>Dictionaries</strong>: Key-value pairs (e.g., {"Iran": 90, "Turkey": 60, "Germany": 80})</li>
        <li><strong>Tuples</strong>: Immutable ordered collections (e.g., (3, 5, 6, 8))</li>
    </ul>
</p>


In [4]:
a = 10
b = 3

print(a + b)  # Addition → 13
print(a - b)  # Subtraction → 7
print(a * b)  # Multiplication → 30
print(a / b)  # Division → 3.3333...
print(a // b) # Floor division → 3
print(a % b)  # Modulus → 1
print(a ** b) # Exponentiation (10^3) → 1000


13
7
30
3.3333333333333335
3
1
1000


<div>
     <h2> Strings </h2>
</div>

| Method | Description | Example | Output |
|--------|-------------|---------|--------|
| `upper()` | Converts the string to uppercase. | `"hello".upper()` | `"HELLO"` |
| `lower()` | Converts the string to lowercase. | `"HELLO".lower()` | `"hello"` |
| `title()` | Capitalizes the first letter of each word. | `"hello world".title()` | `"Hello World"` |
| `capitalize()` | Capitalizes the first letter of the string. | `"python".capitalize()` | `"Python"` |
| `strip()` | Removes leading and trailing whitespace. | `"  hello  ".strip()` | `"hello"` |
| `lstrip()` | Removes leading whitespace. | `"  hello  ".lstrip()` | `"hello  "` |
| `rstrip()` | Removes trailing whitespace. | `"  hello  ".rstrip()` | `"  hello"` |
| `replace(old, new)` | Replaces occurrences of `old` with `new`. | `"hello world".replace("world", "Python")` | `"hello Python"` |
| `split(separator)` | Splits the string into a list. | `"apple,banana,grape".split(",")` | `['apple', 'banana', 'grape']` |
| `join(iterable)` | Joins elements of an iterable into a string. | `"-".join(["a", "b", "c"])` | `"a-b-c"` |
| `find(substring)` | Returns the index of the first occurrence of `substring`. | `"hello".find("l")` | `2` |
| `index(substring)` | Same as `find()`, but raises an error if not found. | `"hello".index("l")` | `2` |
| `count(substring)` | Counts occurrences of `substring`. | `"banana".count("a")` | `3` |
| `startswith(prefix)` | Checks if the string starts with `prefix`. | `"hello".startswith("he")` | `True` |
| `endswith(suffix)` | Checks if the string ends with `suffix`. | `"hello".endswith("o")` | `True` |
| `isdigit()` | Checks if the string consists only of digits. | `"123".isdigit()` | `True` |
| `isalpha()` | Checks if the string consists only of letters. | `"hello".isalpha()` | `True` |
| `isalnum()` | Checks if the string consists only of letters and digits. | `"hello123".isalnum()` | `True` |
| `isspace()` | Checks if the string consists only of whitespace. | `"   ".isspace()` | `True` |
| `swapcase()` | Swaps uppercase and lowercase letters. | `"Hello".swapcase()` | `"hELLO"` |
| `zfill(width)` | Pads the string with zeros until it reaches `width` length. | `"42".zfill(5)` | `"00042"` |


<div>
     <h2> Lists </h2>
</div>

| Method                  | Description                                                    | Example               |
|-------------------------|----------------------------------------------------------------|-----------------------|
| `append(x)`             | Adds item `x` to the end of the list.                         | `lst.append(5)`       |
| `extend(iterable)`      | Extends the list by appending elements from an iterable.       | `lst.extend([6, 7])`  |
| `insert(i, x)`          | Inserts item `x` at position `i`.                             | `lst.insert(1, 5)`    |
| `remove(x)`             | Removes the first occurrence of item `x`.                     | `lst.remove(5)`       |
| `pop([i])`              | Removes and returns the item at position `i`.                 | `lst.pop(2)`          |
| `clear()`               | Removes all items from the list.                              | `lst.clear()`         |
| `index(x[, start, end])`| Returns the index of the first occurrence of item `x`.        | `lst.index(3)`        |
| `count(x)`              | Returns the number of occurrences of item `x`.                | `lst.count(3)`        |
| `sort(key, reverse)`    | Sorts the list in ascending order.                            | `lst.sort(reverse=True)`|
| `reverse()`             | Reverses the elements of the list in place.                   | `lst.reverse()`       |
| `copy()`                | Returns a shallow copy of the list.                           | `lst_copy = lst.copy()`|
| `join()`                | Joins the elements of a list of strings into one string.      | `", ".join(lst)`      |

In [10]:
# Creating a list
lst = [1, 2, 3, 4]
lst

[1, 2, 3, 4]

In [12]:
# append() - Adds an element to the end
lst.append(5)

In [14]:
lst

[1, 2, 3, 4, 5]

In [16]:
# extend() - Adds multiple elements
lst.extend([6, 7])  
lst

[1, 2, 3, 4, 5, 6, 7]

In [18]:
# insert() - Inserts an element at a specific index
lst.insert(2, 10) 
lst

[1, 2, 10, 3, 4, 5, 6, 7]

In [20]:
# remove() - Removes the first occurrence of an element
lst.remove(10)

In [22]:
# pop() - Removes and returns an element (default is last element)
removed_item = lst.pop(1) 

In [24]:
removed_item

2

In [26]:
lst.clear() 

In [28]:
lst

[]

In [30]:
lst = [1, 2, 3, 4]
index_of_3 = lst.index(3)
index_of_3

2

In [32]:
list[1]= 90
list

TypeError: 'type' object does not support item assignment

In [34]:
# count() - Counts occurrences of an element
lst.count(3)

1

In [36]:
# sort() - Sorts the list in ascending order
lst = [4, 1, 3, 2]
lst.sort() 

In [38]:
lst

[1, 2, 3, 4]

In [40]:
# reverse() - Reverses the order of the list
lst.reverse()
lst

[4, 3, 2, 1]

In [42]:
# copy() - Creates a copy of the list
lst_copy = lst.copy() 

In [44]:
words = ["Python", "is", "fun"]
sentence = " ".join(words)
sentence

'Python is fun'

In [46]:
words

['Python', 'is', 'fun']

In [48]:
#Selecting in Lists
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 19, 11, 12, 14, 19, 20]

In [50]:
list[1]

2

In [52]:
list[:5]

[1, 2, 3, 4, 5]

In [54]:
zz = list[-1]
type(zz)

int

In [56]:
#list[start:stop:step]
list[1:5:2]

[2, 4]

In [58]:
list2 =[[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
jj = list2[0]
type(jj)

list

In [60]:
list2[0][1]

2

In [63]:
min(list2)

[1, 2, 3]

In [65]:
sum(list)

140

In [67]:
len(list2)

3

In [69]:
2 in list

True

In [71]:
list3 = [x**2 for x in range(6)]
list3

[0, 1, 4, 9, 16, 25]

In [73]:
numbers = [10, 20, 30, 40, 50]

In [75]:
max(numbers)

50

In [77]:
sum(numbers)

150

In [79]:
len(numbers)

5

<div>
    <h4>"The problem with lists is that we cannot directly perform mathematical operations on them. To handle numerical computations efficiently, we can use arrays instead. We'll work on that later."
    </h4>
</div>

In [82]:
numbers *2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

<div>
    <h1>
        Dictionary
    </h1>
</div>

In [85]:
data = {"name": "Alice", "age": 25}

In [87]:
data.keys()        # Returns dict_keys(['name', 'age'])
data.values()      # Returns dict_values(['Alice', 25])
data.items()       # Returns dict_items([('name', 'Alice'), ('age', 25)])
data.get("name")   # Get value of key → "Alice"
data.update({"city": "Berlin"})  # Adds new key-value pair
data.pop("age")    # Removes key "age"


25

<div>
    <h2>
        Import a package
    </h2>
</div>

<div>
    <h2> Numpy </h2>
</div>

<div>
    <h4>
        The NumPy (numpy) library is used in Python for efficient numerical computing. It provides powerful tools for working with arrays, matrices, and mathematical operations.
    </h4>
</div>

In [92]:
import numpy as np

In [94]:
np.array([1,2,3,4,5,5,6])

array([1, 2, 3, 4, 5, 5, 6])

In [96]:
weight = np.array([67, 72, 89, 90])

In [98]:
weight *2

array([134, 144, 178, 180])

In [100]:
y = np.array ([[3,5,6,7],
               [6,7,8,9],
               [7,8,9,1]])

In [102]:
y

array([[3, 5, 6, 7],
       [6, 7, 8, 9],
       [7, 8, 9, 1]])

In [104]:
y[1]

array([6, 7, 8, 9])

In [106]:
y[2][0]

7

In [108]:
y[0:2,2:]

array([[6, 7],
       [8, 9]])

In [110]:
y > 6

array([[False, False, False,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False]])

In [112]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [114]:
type(y)

numpy.ndarray

In [116]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
# Basic Properties of NumPy Arrays
arr.shape

(2, 3)

In [120]:
arr.ndim

2

In [122]:
arr.size

6

In [124]:
arr.dtype

dtype('int64')

In [126]:
arr.itemsize

8

In [128]:
arr.nbytes

48

<div>
    <h2> NumPy Methods (Functions Inside an Array)
    </h2>
</div>

In [131]:
#Array Manipulation Methods
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
arr2.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [135]:
arr2.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [137]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
arr2.copy()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [141]:
# Mathematical & Statistical Methods
arr3 = np.array([1, 3, 6, 9, 12, 15])
arr3

array([ 1,  3,  6,  9, 12, 15])

In [143]:
arr3.sum()

46

In [157]:
arr3.min()

1

In [159]:
arr3.max()

15

In [160]:
arr3.mean()

7.666666666666667

In [163]:
arr3.std()

4.887626099538393

In [164]:
arr3.var()

23.888888888888886

In [167]:
arr3.prod()

29160

In [169]:
arr3.cumsum()

array([ 1,  4, 10, 19, 31, 46])

In [171]:
arr.cumprod()

array([  1,   2,   6,  24, 120, 720])

In [108]:
# Sorting & Searching Methods
arr4 = np.array([4,1,5,7,9,0,12,3,40])
arr4

array([ 4,  1,  5,  7,  9,  0, 12,  3, 40])

In [110]:
np.sort(arr4)   # This change will apply on arr4

array([ 0,  1,  3,  4,  5,  7,  9, 12, 40])

In [177]:
np.argsort(arr4)

array([5, 1, 7, 0, 2, 3, 4, 6, 8], dtype=int64)

In [179]:
np.where(arr4 > 8)

(array([4, 6, 8], dtype=int64),)

In [181]:
# Basic Mathematical Functions
np.add(arr4,100)   # not permanent

array([104, 101, 105, 107, 109, 100, 112, 103, 140])

In [183]:
np.subtract(arr4,1)

array([ 3,  0,  4,  6,  8, -1, 11,  2, 39])

In [185]:
np.multiply(arr4, 2)

array([ 8,  2, 10, 14, 18,  0, 24,  6, 80])

In [187]:
np.divide(arr4, 2)

array([ 2. ,  0.5,  2.5,  3.5,  4.5,  0. ,  6. ,  1.5, 20. ])

In [189]:
np.power(arr4, 2)

array([  16,    1,   25,   49,   81,    0,  144,    9, 1600], dtype=int32)

In [191]:
print(np.random.randint(1, 10, 5)) # 5 random integers from 1 to 9
print(np.random.rand(3))           # 3 random floats (0 to 1)
print(np.random.normal(0, 1, 5))   # 5 random numbers from normal distribution

[3 3 7 2 4]
[0.49111893 0.78002776 0.41092437]
[-1.07746533  0.23848917  1.67960037 -1.30580313 -1.13889525]


In [193]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [195]:
x = np.array([1, 2, 3])
z = np.array([4, 5, 6])

In [197]:
np.vstack([x,z])

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
np.hstack([x,z])

array([1, 2, 3, 4, 5, 6])

In [201]:
arr5 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [5, 9, 0, 3]])

In [203]:
arr5[1]

array([5, 6, 7, 8])

In [205]:
arr5[0][1]

2

In [207]:
arr5[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [209]:
arr5[:,2:]

array([[3, 4],
       [7, 8],
       [0, 3]])

In [211]:
arr5 > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [213]:
arr5[arr5 > 4]

array([5, 6, 7, 8, 5, 9])

<div>
    <h2> Pandas</h2>
</div>

<div>
    <h4>
        Pandas is a Python library used for data manipulation, analysis, and cleaning. It provides fast and flexible tools to work with structured data, such as tables (DataFrames) and series (1D data). </h4>
</div>

<p>
    Key Reasons to Use Pandas:
    <ul>
        <li> Handles large datasets efficiently</li>
        <li> Supports data cleaning and preprocessing</li>
        <li> Works well with NumPy, Matplotlib, and SQL</li>
        <li> Provides built-in statistical and mathematical functions</li>
        <li> Can read and write multiple file formats (CSV, Excel, SQL, JSON, etc.)</li>
    </ul>
</p>


In [146]:
import pandas as pd

<div>
    <h2>
        DataFrame
    </h2>
</div>

In [151]:
# Create a DataFrame from a Dictionary
data = {
    "name" : ["alice", "anna", "jack", "july"],
    "lastname" : ["kepit", "kia", "muler" , "summet"],
    "age" : [24, 28, 25, 31],
    "job" : ["student", "engineer", "doctor", "teacher"]
}
print(data)

{'name': ['alice', 'anna', 'jack', 'july'], 'lastname': ['kepit', 'kia', 'muler', 'summet'], 'age': [24, 28, 25, 31], 'job': ['student', 'engineer', 'doctor', 'teacher']}


In [155]:
df = pd.DataFrame(data)
df

name lastname  age       job
0  alice    kepit   24   student
1   anna      kia   28  engineer
2   jack    muler   25    doctor
3   july   summet   31   teacher

In [157]:
# DataFrame Properties (Attributes)
df.shape

(4, 4)

In [226]:
df.size

16

In [228]:
df.dtypes

name        object
lastname    object
age          int64
job         object
dtype: object

In [230]:
df.columns

Index(['name', 'lastname', 'age', 'job'], dtype='object')

In [232]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [234]:
# Access a Single Column
df[["name"]]

name
0  alice
1   anna
2   jack
3   july

In [236]:
df[["name", "job"]]

name       job
0  alice   student
1   anna  engineer
2   jack    doctor
3   july   teacher

In [238]:
# loc & iloc
df.loc[1]

name            anna
lastname         kia
age               28
job         engineer
Name: 1, dtype: object

In [240]:
print(df.iloc[1])

name            anna
lastname         kia
age               28
job         engineer
Name: 1, dtype: object


In [242]:
df.info

<bound method DataFrame.info of     name lastname  age       job
0  alice    kepit   24   student
1   anna      kia   28  engineer
2   jack    muler   25    doctor
3   july   summet   31   teacher>

In [244]:
df.describe()

age
count   4.000000
mean   27.000000
std     3.162278
min    24.000000
25%    24.750000
50%    26.500000
75%    28.750000
max    31.000000

In [246]:
df.sort_values(by = "age")

name lastname  age       job
0  alice    kepit   24   student
2   jack    muler   25    doctor
1   anna      kia   28  engineer
3   july   summet   31   teacher

In [248]:
df[df["age"] > 26]

name lastname  age       job
1  anna      kia   28  engineer
3  july   summet   31   teacher

In [250]:
# Adding a New Column
df["sex"] = ["F", "F", "M", "F" ]
df

name lastname  age       job sex
0  alice    kepit   24   student   F
1   anna      kia   28  engineer   F
2   jack    muler   25    doctor   M
3   july   summet   31   teacher   F

In [252]:
# Dropping a column
df.drop(columns = ['age'])

name lastname       job sex
0  alice    kepit   student   F
1   anna      kia  engineer   F
2   jack    muler    doctor   M
3   july   summet   teacher   F

In [254]:
# Dropping a row
df.drop(index = 1)

name lastname  age      job sex
0  alice    kepit   24  student   F
2   jack    muler   25   doctor   M
3   july   summet   31  teacher   F

<div>
    <h3> some exercises
    </h3>
</div>

In [257]:
df = pd.DataFrame(np.arange(12).reshape(3,4), columns = ["G1", "G2", "G3", "G4"])
df

G1  G2  G3  G4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11

In [259]:
df.drop([0])

G1  G2  G3  G4
1   4   5   6   7
2   8   9  10  11

In [261]:
df.drop(["G2"], axis =1)

G1  G3  G4
0   0   2   3
1   4   6   7
2   8  10  11

In [263]:
df.insert(4, "G5", [4,6,7])

In [265]:
df

G1  G2  G3  G4  G5
0   0   1   2   3   4
1   4   5   6   7   6
2   8   9  10  11   7

In [267]:
df["G1"]

0    0
1    4
2    8
Name: G1, dtype: int32

In [269]:
df[["G1", "G5"]]

G1  G5
0   0   4
1   4   6
2   8   7

In [271]:
df.loc[1,]

G1    4
G2    5
G3    6
G4    7
G5    6
Name: 1, dtype: int64

In [273]:
df.loc[1,"G5"]

6

In [274]:
df.loc[[1,]]

G1  G2  G3  G4  G5
1   4   5   6   7   6

In [277]:
df.loc[[0, 1, 2], ["G1", "G2"]]

G1  G2
0   0   1
1   4   5
2   8   9

In [297]:
df.iloc[[0,1], [0,1]]

G1  G2
0   0   1
1   4   5

In [299]:
df2 = pd.DataFrame(np.arange(16).reshape(4,4), columns= ["C1" , "C2", "C3", "C4" ])
df2

C1  C2  C3  C4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [301]:
df2.sort_values(["C2"]) 

C1  C2  C3  C4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [303]:
df2["C2"] ==1

0     True
1    False
2    False
3    False
Name: C2, dtype: bool

In [305]:
df2[df2["C2"]==1]

C1  C2  C3  C4
0   0   1   2   3

In [309]:
df2[(df2["C2"]==1) | (df2["C2"]==5)]

C1  C2  C3  C4
0   0   1   2   3
1   4   5   6   7

In [311]:
df2[(df2["C2"]==1) & (df2["C1"]==0)]

C1  C2  C3  C4
0   0   1   2   3

In [323]:
x = np.logical_or(df2["C1"] == 4, df2["C2"]==0)

In [325]:
df2[x]

C1  C2  C3  C4
1   4   5   6   7

In [331]:
df2[np.logical_and(df2["C2"]==13,df2["C4"]==15)]

C1  C2  C3  C4
3  12  13  14  15

In [335]:
#.isin
y = df2["C2"].isin([1,5,13])
df2[y]

C1  C2  C3  C4
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [363]:
data = np.random.rand(10,5)
data

array([[0.40600317, 0.7466565 , 0.51230827, 0.22897383, 0.30117051],
       [0.15163937, 0.60664452, 0.95508608, 0.91777906, 0.26447308],
       [0.89396664, 0.32602418, 0.4690327 , 0.23594364, 0.67175846],
       [0.79684702, 0.31528727, 0.36691845, 0.71575166, 0.70381881],
       [0.52505781, 0.41570013, 0.40764601, 0.63861839, 0.58412934],
       [0.21884215, 0.45177314, 0.49910727, 0.11278189, 0.46630949],
       [0.42895061, 0.58015023, 0.15946149, 0.17678508, 0.48128785],
       [0.9111408 , 0.65099294, 0.29496463, 0.1947107 , 0.00135619],
       [0.69747131, 0.40051868, 0.17658725, 0.01853731, 0.40676329],
       [0.84954299, 0.33942047, 0.91691634, 0.15705039, 0.77253285]])

In [365]:
df = pd.DataFrame(data, [2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029], ["Canada", "USA", "China", "Italy", "France"])
df

Canada       USA     China     Italy    France
2020  0.406003  0.746657  0.512308  0.228974  0.301171
2021  0.151639  0.606645  0.955086  0.917779  0.264473
2022  0.893967  0.326024  0.469033  0.235944  0.671758
2023  0.796847  0.315287  0.366918  0.715752  0.703819
2024  0.525058  0.415700  0.407646  0.638618  0.584129
2025  0.218842  0.451773  0.499107  0.112782  0.466309
2026  0.428951  0.580150  0.159461  0.176785  0.481288
2027  0.911141  0.650993  0.294965  0.194711  0.001356
2028  0.697471  0.400519  0.176587  0.018537  0.406763
2029  0.849543  0.339420  0.916916  0.157050  0.772533

In [369]:
df["Hungery"] = np.random.rand(10,1)

In [374]:
df

Canada       USA     China     Italy    France   Hungery
2020  0.406003  0.746657  0.512308  0.228974  0.301171  0.986520
2021  0.151639  0.606645  0.955086  0.917779  0.264473  0.365165
2022  0.893967  0.326024  0.469033  0.235944  0.671758  0.225941
2023  0.796847  0.315287  0.366918  0.715752  0.703819  0.462242
2024  0.525058  0.415700  0.407646  0.638618  0.584129  0.843370
2025  0.218842  0.451773  0.499107  0.112782  0.466309  0.123360
2026  0.428951  0.580150  0.159461  0.176785  0.481288  0.742805
2027  0.911141  0.650993  0.294965  0.194711  0.001356  0.584605
2028  0.697471  0.400519  0.176587  0.018537  0.406763  0.671372
2029  0.849543  0.339420  0.916916  0.157050  0.772533  0.563398

In [378]:
df["Canada"].mean()

0.5879461861535991

In [397]:
df.mean()

Canada     0.587946
USA        0.483317
China      0.475803
Italy      0.339693
France     0.465360
Hungery    0.556878
dtype: float64

In [400]:
df.mean(axis=1)

2020    0.530272
2021    0.543465
2022    0.470444
2023    0.560144
2024    0.569087
2025    0.312029
2026    0.428240
2027    0.439628
2028    0.395208
2029    0.599810
dtype: float64

In [415]:
pd2 = pd.DataFrame({
    "name": ["A", "M", "L", "J", "I", "V", "D", "F"],
    "color": ["Red", "Black", "Green","Red", "Black","Black", "Green","Red"],
    "age": [22, 34, 20, 22, 28, 20, 30, 23],
    "country": ["China", "France", "USA","China", "France", "USA", "USA", "France"]
})

In [431]:
pd2

name  color  age country
0    A    Red   22   China
1    M  Black   34  France
2    L  Green   20     USA
3    J    Red   22   China
4    I  Black   28  France
5    V  Black   20     USA
6    D  Green   30     USA
7    F    Red   23  France

In [443]:
pd.DataFrame(pd2.groupby(["color", "country"])["age"].mean())


age
color country      
Black France   31.0
      USA      20.0
Green USA      25.0
Red   China    22.0
      France   23.0

<div>
    <h1>
        string methods
    </h1>
</div>